### ISSUE TITLE
Feature Request: more specific meta for topic/... / etc

### ISSUE THREAD

**Issue by anig1scur** [0xasahi/neogroup#1]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/52899668/217781863-06e43660-deea-4612-a2ae-78cea312c894.png">

It should be resolved to the topic's title and description

**Comment by 0xasahi** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/18495/217816127-015e7b74-ebf9-4ea9-8cb4-3c361baecb29.png">

Thanks, fixed
